### ISSUE TITLE
node server wss://127.0.0.1:8888/kurento

### ISSUE THREAD

**Issue by dphov** [mariogasparoni/kurento-monitor#1]
WARNING: No configurations found in configuration directory:/root/kurento-monitor-master/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/root/kurento-monitor-master/node_modules/config/lib/config.js:181
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "file_output" is not defined
    at Config.get (/root/kurento-monitor-master/node_modules/config/lib/config.js:181:11)
    at Object.<anonymous> (/root/kurento-monitor-master/server.js:10:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

**Comment by mariogasparoni** [comment]
Hi, @dphov .

You have to create a config file called default.json in config folder.
You can simply use/copy the example config file (config/default.example.json file)

**Comment by dphov** [comment]
@mariogasparoni, Thanks!
